READme.md
jnadroj/thxmx-ui pull request #30
Opened 2022-10-13 18:25 UTC by Dorcastunmise

READme.md Edit 
Includes addition of new sections & linkage to CONTRIBUTION.md

2022-10-13 20:48 UTC, jnadroj commented on README.md
> +  1.  Install Vite tool first
can we eliminate the part of creating the vite project from scratch?

2022-10-13 20:51 UTC, jnadroj commented on README.md
> +  5. Install devDependencies listed below 👇🏻👇🏼👇🏽👇🏾👇🏿
can we eliminate the part of creating the vite project from scratch? 
```suggestion

```

2022-10-13 20:52 UTC, jnadroj commented on README.md
> +
```suggestion
Clone or Download the repository 
    <pre>git clone https://thxmx-ui.netlify.app/ </pre>

Install dependencies 
        <pre>npm install</pre>
        
Run the proyect 
    <pre>npm run dev</pre>
```

2022-10-13 20:53 UTC, jnadroj commented on README.md
> +<pre>npm i acorn-jsx acorn-jsx </pre>
```suggestion
## Run the storybook 

    <pre>npm run storybook</pre>
```

2022-10-13 20:54 UTC, jnadroj commented on README.md
> +dev.to/jordandev (Blog)
```suggestion
```

2022-10-13 20:55 UTC, jnadroj requested changes
please the comments I posted can be improved by taking your personal considerations into account.

2022-10-14 01:42 UTC, djra26111990 approved these changes

2022-10-14 02:17 UTC, merged